import React from 'react'
import Image from 'next/image'

export const metadata = {
  title: 'Privacy Policy - Beautique Nails & Spa',
  description: 'Privacy Policy for Beautique Nails & Spa Lucky Wheel promotion.',
}

export default function PolicyPage() {
  return (
    <main className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-black border-b-[4px] border-[#F8DC65] py-[24px] flex items-center justify-center">
        <a href="/">
          <Image
            src="/figma/logo.png"
            alt="Beautique Nails & Spa"
            width={100}
            height={48}
            className="h-[48px] w-[100px]"
            priority
          />
        </a>
      </header>

      {/* Content */}
      <article
        className="max-w-[800px] mx-auto px-6 py-[48px]"
        style={{ fontFamily: 'var(--font-clash)' }}
      >
        <h1 className="text-[32px] leading-[1.3] font-medium text-black mb-[8px]">
          Privacy Policy
        </h1>
        <p className="text-[14px] text-gray-500 mb-[32px]">
          Last updated: February 05, 2026
        </p>

        <div className="space-y-[20px] text-[15px] leading-[1.8] text-gray-800">
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and
            disclosure of Your information when You use the Service and tells You about Your privacy
            rights and how the law protects You.
          </p>
          <p>
            We use Your Personal Data to provide and improve the Service. By using the Service, You
            agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-[24px] font-medium text-black pt-[16px]">
            Interpretation and Definitions
          </h2>

          <h3 className="text-[18px] font-medium text-black">Interpretation</h3>
          <p>
            The words whose initial letters are capitalized have meanings defined under the following
            conditions. The following definitions shall have the same meaning regardless of whether
            they appear in singular or in plural.
          </p>

          <h3 className="text-[18px] font-medium text-black">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-[24px] space-y-[8px]">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Top Card Solution Ltd, 8655 Charleston Creek Dr, Mason, OH-45040.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Ohio, United States.</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual. We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to topcardsolution.com, accessible from topcardsolution.com.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="text-[24px] font-medium text-black pt-[16px]">
            Collecting and Using Your Personal Data
          </h2>

          <h3 className="text-[18px] font-medium text-black">Types of Data Collected</h3>

          <h4 className="text-[16px] font-medium text-black">Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable
            information that can be used to contact or identify You. Personally identifiable information
            may include, but is not limited to:
          </p>
          <ul className="list-disc pl-[24px] space-y-[4px]">
            <li>Email address</li>
            <li>First name and last name</li>
          </ul>

          <h4 className="text-[16px] font-medium text-black">Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. Usage Data may include information
            such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your visit, the time spent on those
            pages, unique device identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information
            automatically, including, but not limited to, the type of mobile device You use, Your mobile
            device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type
            of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>

          <h3 className="text-[18px] font-medium text-black">Tracking Technologies and Cookies</h3>
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and
            store certain information. Tracking technologies We use include beacons, tags, and scripts
            to collect and track information and to improve and analyze Our Service.
          </p>
          <ul className="list-disc pl-[24px] space-y-[8px]">
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
            <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
          </ul>
          <p>
            Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal
            computer or mobile device when You go offline, while Session Cookies are deleted as soon as
            You close Your web browser.
          </p>
          <p>
            Where required by law, we use non-essential cookies (such as analytics, advertising, and
            remarketing cookies) only with Your consent. You can withdraw or change Your consent at
            any time using Our cookie preferences tool (if available) or through Your browser/device settings.
          </p>

          <p>We use both Session and Persistent Cookies for the purposes set out below:</p>

          <div className="pl-[16px] space-y-[16px]">
            <div>
              <p className="font-medium text-black">Necessary / Essential Cookies</p>
              <p>Type: Session Cookies — Administered by: Us</p>
              <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</p>
            </div>
            <div>
              <p className="font-medium text-black">Cookies Policy / Notice Acceptance Cookies</p>
              <p>Type: Persistent Cookies — Administered by: Us</p>
              <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            </div>
            <div>
              <p className="font-medium text-black">Functionality Cookies</p>
              <p>Type: Persistent Cookies — Administered by: Us</p>
              <p>Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.</p>
            </div>
          </div>

          <h3 className="text-[18px] font-medium text-black">Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc pl-[24px] space-y-[8px]">
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
            <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
          </ul>

          <p>We may share Your Personal Data in the following situations:</p>
          <ul className="list-disc pl-[24px] space-y-[8px]">
            <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
            <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
            <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
            <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
            <li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
            <li><strong>With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
          </ul>

          <h3 className="text-[18px] font-medium text-black">Retention of Your Personal Data</h3>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes
            set out in this Privacy Policy. We will retain and use Your Personal Data to the extent
            necessary to comply with our legal obligations, resolve disputes, and enforce our legal
            agreements and policies.
          </p>
          <p>
            Where possible, We apply shorter retention periods and/or reduce identifiability by deleting,
            aggregating, or anonymizing data.
          </p>

          <div className="pl-[16px] space-y-[12px]">
            <div>
              <p className="font-medium text-black">Account Information</p>
              <p>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure.</p>
            </div>
            <div>
              <p className="font-medium text-black">Customer Support Data</p>
              <p>Support tickets and correspondence: up to 24 months from the date of ticket closure.</p>
              <p>Chat transcripts: up to 24 months for quality assurance and staff training purposes.</p>
            </div>
            <div>
              <p className="font-medium text-black">Usage Data</p>
              <p>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection.</p>
              <p>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</p>
            </div>
          </div>

          <p>We may retain Personal Data beyond the periods stated above for different reasons:</p>
          <ul className="list-disc pl-[24px] space-y-[4px]">
            <li>Legal obligation: We are required by law to retain specific data.</li>
            <li>Legal claims: Data is necessary to establish, exercise, or defend legal claims.</li>
            <li>Your explicit request: You ask Us to retain specific information.</li>
            <li>Technical limitations: Data exists in backup systems that are scheduled for routine deletion.</li>
          </ul>

          <p>When retention periods expire, We securely delete or anonymize Personal Data according to the following procedures:</p>
          <ul className="list-disc pl-[24px] space-y-[4px]">
            <li><strong>Deletion:</strong> Personal Data is removed from Our systems and no longer actively processed.</li>
            <li><strong>Backup retention:</strong> Residual copies may remain in encrypted backups for a limited period.</li>
            <li><strong>Anonymization:</strong> In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You.</li>
          </ul>

          <h3 className="text-[18px] font-medium text-black">Transfer of Your Personal Data</h3>
          <p>
            Your information, including Personal Data, is processed at the Company&apos;s operating offices
            and in any other places where the parties involved in the processing are located. It means
            that this information may be transferred to — and maintained on — computers located
            outside of Your state, province, country or other governmental jurisdiction where the data
            protection laws may differ from those from Your jurisdiction.
          </p>
          <p>
            Where required by applicable law, We will ensure that international transfers of Your
            Personal Data are subject to appropriate safeguards. The Company will take all steps
            reasonably necessary to ensure that Your data is treated securely and in accordance with
            this Privacy Policy.
          </p>

          <h3 className="text-[18px] font-medium text-black">Delete Your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting the Personal Data that We
            have collected about You. Our Service may give You the ability to delete certain information
            about You from within the Service.
          </p>
          <p>
            You may update, amend, or delete Your information at any time by signing in to Your Account,
            if you have one, and visiting the account settings section that allows you to manage Your
            personal information. You may also contact Us to request access to, correct, or delete any
            Personal Data that You have provided to Us.
          </p>

          <h2 className="text-[24px] font-medium text-black pt-[16px]">
            Disclosure of Your Personal Data
          </h2>

          <h3 className="text-[18px] font-medium text-black">Business Transactions</h3>
          <p>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
            transferred. We will provide notice before Your Personal Data is transferred and becomes
            subject to a different Privacy Policy.
          </p>

          <h3 className="text-[18px] font-medium text-black">Law enforcement</h3>
          <p>
            Under certain circumstances, the Company may be required to disclose Your Personal Data
            if required to do so by law or in response to valid requests by public authorities (e.g. a court
            or a government agency).
          </p>

          <h3 className="text-[18px] font-medium text-black">Other legal requirements</h3>
          <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul className="list-disc pl-[24px] space-y-[4px]">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h3 className="text-[18px] font-medium text-black">Security of Your Personal Data</h3>
          <p>
            The security of Your Personal Data is important to Us, but remember that no method of
            transmission over the Internet, or method of electronic storage is 100% secure. While We
            strive to use commercially reasonable means to protect Your Personal Data, We cannot
            guarantee its absolute security.
          </p>

          <h2 className="text-[24px] font-medium text-black pt-[16px]">
            Children&apos;s Privacy
          </h2>
          <p>
            Our Service does not address anyone under the age of 16. We do not knowingly collect
            personally identifiable information from anyone under the age of 16. If You are a parent or
            guardian and You are aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data from anyone under
            the age of 16 without verification of parental consent, We take steps to remove that
            information from Our servers.
          </p>

          <h2 className="text-[24px] font-medium text-black pt-[16px]">
            Links to Other Websites
          </h2>
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a
            third party link, You will be directed to that third party&apos;s site. We strongly advise You to
            review the Privacy Policy of every site You visit. We have no control over and assume no
            responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>

          <h2 className="text-[24px] font-medium text-black pt-[16px]">
            Changes to this Privacy Policy
          </h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by
            posting the new Privacy Policy on this page. We will let You know via email and/or a
            prominent notice on Our Service, prior to the change becoming effective and update the
            &quot;Last updated&quot; date at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this
            Privacy Policy are effective when they are posted on this page.
          </p>

          <h2 className="text-[24px] font-medium text-black pt-[16px]">
            Contact Us
          </h2>
          <p>
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <ul className="list-disc pl-[24px]">
            <li>By email: <a href="mailto:support@topcardsolution.com" className="text-[#BA1640] underline">support@topcardsolution.com</a></li>
          </ul>
        </div>
      </article>

      {/* Footer */}
      <footer className="bg-black border-t-[2px] border-[#F8DC65] py-[24px] flex items-center justify-center">
        <p
          className="text-[#F8DC65] text-[14px] leading-[1.5] text-center px-6"
          style={{ fontFamily: 'var(--font-clash)' }}
        >
          © 2025 Nail Salon &amp; Spa Lucky Wheel • All rights reserved
        </p>
      </footer>
    </main>
  )
}
